<thead>
<tr>
    <th>#</th>
    <th>{{__('dashboard.username')}}</th>
    <th>{{__('validation.attributes.email')}}</th>
    <th>{{__('user.permission')}}</th>
    <th>{{__('user.register_time')}}</th>
    <th>{{__('dashboard.setting')}}</th>
</tr>
</thead>
