<link rel="stylesheet" href="{{asset('/app/css/linearicons.css')}}">
<link rel="stylesheet" href="{{asset('/app/css/font-awesome.min.css')}}">
<link rel="stylesheet" href="{{asset('/app/css/bootstrap.css')}}">
<link rel="stylesheet" href="{{asset('/app/css/magnific-popup.css')}}">
<link rel="stylesheet" href="{{asset('/app/css/nice-select.css')}}">
<link rel="stylesheet" href="{{asset('/app/css/animate.min.css')}}">
<link rel="stylesheet" href="{{asset('/app/css/owl.carousel.css')}}">
<link rel="stylesheet" href="{{asset('/app/css/jquery-ui.css')}}">
<link rel="stylesheet" href="{{asset('/app/css/main.css')}}">
