<thead>
<tr>
    <th>#</th>
    <th>{{__('validation.attributes.name')}}</th>
    <th>{{__('validation.attributes.url')}}</th>
    <th>{{__('menu.parent')}}</th>
    <th>{{__('dashboard.setting')}}</th>
</tr>
</thead>
